// <auto-generated />
using System;
using FunctionExecutor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunctionExecutor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FunctionExecutor.Models.CostCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmicCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Labor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Materials")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Other")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CostCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CmicCode = "LAB-000",
                            Labor = 0m,
                            Materials = 0m,
                            Name = "Labor",
                            Other = 0m,
                            Qty = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 2,
                            CmicCode = "MAT-000",
                            Labor = 0m,
                            Materials = 0m,
                            Name = "Materials",
                            Other = 0m,
                            Qty = 0m,
                            TotalCost = 0m
                        },
                        new
                        {
                            Id = 3,
                            CmicCode = "LAB-001",
                            Labor = 5000m,
                            Materials = 0m,
                            Name = "Direct Labor",
                            Other = 0m,
                            ParentId = 1,
                            Qty = 1m,
                            TotalCost = 5000m
                        },
                        new
                        {
                            Id = 4,
                            CmicCode = "LAB-002",
                            Labor = 2000m,
                            Materials = 0m,
                            Name = "Indirect Labor",
                            Other = 0m,
                            ParentId = 1,
                            Qty = 1m,
                            TotalCost = 2000m
                        },
                        new
                        {
                            Id = 5,
                            CmicCode = "LAB-001-01",
                            Labor = 2500m,
                            Materials = 0m,
                            Name = "Carpenter",
                            Other = 0m,
                            ParentId = 3,
                            Qty = 1m,
                            TotalCost = 2500m
                        },
                        new
                        {
                            Id = 6,
                            CmicCode = "LAB-001-02",
                            Labor = 2500m,
                            Materials = 0m,
                            Name = "Electrician",
                            Other = 0m,
                            ParentId = 3,
                            Qty = 1m,
                            TotalCost = 2500m
                        },
                        new
                        {
                            Id = 7,
                            CmicCode = "MAT-001",
                            Labor = 0m,
                            Materials = 3000m,
                            Name = "Lumber",
                            Other = 0m,
                            ParentId = 2,
                            Qty = 100m,
                            TotalCost = 3000m
                        },
                        new
                        {
                            Id = 8,
                            CmicCode = "MAT-002",
                            Labor = 0m,
                            Materials = 1500m,
                            Name = "Electrical",
                            Other = 0m,
                            ParentId = 2,
                            Qty = 50m,
                            TotalCost = 1500m
                        },
                        new
                        {
                            Id = 9,
                            CmicCode = "MAT-003",
                            Labor = 0m,
                            Materials = 500m,
                            Name = "Hardware",
                            Other = 0m,
                            ParentId = 2,
                            Qty = 200m,
                            TotalCost = 500m
                        });
                });

            modelBuilder.Entity("FunctionExecutor.Models.Workbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workbooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test workbook with sample cost codes for Excel calculation",
                            Name = "Sample Construction Project",
                            TemplateFilePath = "sample-calculation.xlsx",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        });
                });

            modelBuilder.Entity("FunctionExecutor.Models.WorkbookCostCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CmicCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CostCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Labor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Materials")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Other")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkbookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CostCodeId");

                    b.HasIndex("WorkbookId", "CmicCode");

                    b.ToTable("WorkbookCostCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CmicCode = "LAB-000",
                            CostCodeId = 1,
                            Labor = 0m,
                            Materials = 0m,
                            Name = "Labor",
                            Other = 0m,
                            Qty = 0m,
                            TotalCost = 0m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 2,
                            CmicCode = "MAT-000",
                            CostCodeId = 2,
                            Labor = 0m,
                            Materials = 0m,
                            Name = "Materials",
                            Other = 0m,
                            Qty = 0m,
                            TotalCost = 0m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 3,
                            CmicCode = "LAB-001",
                            CostCodeId = 3,
                            Labor = 5000m,
                            Materials = 0m,
                            Name = "Direct Labor",
                            Other = 0m,
                            Qty = 1m,
                            TotalCost = 5000m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 4,
                            CmicCode = "LAB-002",
                            CostCodeId = 4,
                            Labor = 2000m,
                            Materials = 0m,
                            Name = "Indirect Labor",
                            Other = 0m,
                            Qty = 1m,
                            TotalCost = 2000m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 5,
                            CmicCode = "LAB-001-01",
                            CostCodeId = 5,
                            Labor = 2500m,
                            Materials = 0m,
                            Name = "Carpenter",
                            Other = 0m,
                            Qty = 1m,
                            TotalCost = 2500m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 6,
                            CmicCode = "LAB-001-02",
                            CostCodeId = 6,
                            Labor = 2500m,
                            Materials = 0m,
                            Name = "Electrician",
                            Other = 0m,
                            Qty = 1m,
                            TotalCost = 2500m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 7,
                            CmicCode = "MAT-001",
                            CostCodeId = 7,
                            Labor = 0m,
                            Materials = 3000m,
                            Name = "Lumber",
                            Other = 0m,
                            Qty = 100m,
                            TotalCost = 3000m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 8,
                            CmicCode = "MAT-002",
                            CostCodeId = 8,
                            Labor = 0m,
                            Materials = 1500m,
                            Name = "Electrical",
                            Other = 0m,
                            Qty = 50m,
                            TotalCost = 1500m,
                            WorkbookId = 1
                        },
                        new
                        {
                            Id = 9,
                            CmicCode = "MAT-003",
                            CostCodeId = 9,
                            Labor = 0m,
                            Materials = 500m,
                            Name = "Hardware",
                            Other = 0m,
                            Qty = 200m,
                            TotalCost = 500m,
                            WorkbookId = 1
                        });
                });

            modelBuilder.Entity("FunctionExecutor.Models.CostCode", b =>
                {
                    b.HasOne("FunctionExecutor.Models.CostCode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FunctionExecutor.Models.WorkbookCostCode", b =>
                {
                    b.HasOne("FunctionExecutor.Models.CostCode", "CostCode")
                        .WithMany("WorkbookCostCodes")
                        .HasForeignKey("CostCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FunctionExecutor.Models.Workbook", "Workbook")
                        .WithMany("WorkbookCostCodes")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostCode");

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("FunctionExecutor.Models.CostCode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("WorkbookCostCodes");
                });

            modelBuilder.Entity("FunctionExecutor.Models.Workbook", b =>
                {
                    b.Navigation("WorkbookCostCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
